### ISSUE TITLE
add error handling to fetch wrappers 

### ISSUE THREAD

**Issue by asipser** [weblab-workshops/catbook-react#22]
in client/src/utilities.js we need to add error handling so if the server returns a 500, we don't just print out the "cannot parse <" or whatever the weird error is. make sure to comment what it does.

**Comment by nsinghal7** [comment]
It now outputs a message with the failing route, the status if not 200, and any text that couldn't be converted to JSON (in case they return HTML or a string instead of an object).

Potential improvement: I use Body.clone() to clone the fetch result so we can see the text in the debug message. Idk if this has performance implications. If it does, we can replace Body.json() with calls to Body.text() and JSON.parse() to still offer debug messages, but the code is less clear
