### ISSUE TITLE
add header to webpack config file

### ISSUE THREAD

**Issue by asipser** [weblab-workshops/catbook-react#8]
just needs to say students dont have to worry about this file, **except for setting up proxies**.

On that note, is there a clean way of providing students feedback if they might not have proxied a route instead of the request just failing? I feel like there isn't but maybe @cory2067 has an idea?

**Comment by cory2067** [comment]
o that reminds me i guess we can delete
```js
      '/auth': 'http://localhost:3000',
      '/logout': 'http://localhost:3000'
```

currently, i have it set up so that **every** route handled by the server (as opposed to react router) is prefixed by `/api`. 

this includes auth, which is at `POST /api/login`. we can discuss if this is a good design
but the benefit here is that you should never need to add a new line to the proxy
